const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.scrollto,
		C3.Behaviors.Turret,
		C3.Behaviors.EightDir,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Behaviors.Anchor,
		C3.Plugins.Spritefont2,
		C3.Plugins.sliderbar,
		C3.Behaviors.shadowcaster,
		C3.Plugins.Button,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.TextBox,
		C3.Plugins.NinePatch,
		C3.Behaviors.Turret.Cnds.IsEnabled,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Button.Cnds.OnClicked,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.EightDir.Acts.SimulateControl
	];
};
self.C3_JsPropNameTable = [
	{ТайловыйФон: 0},
	{Спрайт: 0},
	{map: 0},
	{Спрайт2: 0},
	{Твердый: 0},
	{Спрайт4: 0},
	{СледитьЗа: 0},
	{Турель: 0},
	{"8Направлений": 0},
	{Спрайт5: 0},
	{Пуля: 0},
	{враг: 0},
	{Клавиатура: 0},
	{mouse: 0},
	{Твёрдый: 0},
	{Спрайт7: 0},
	{Спрайт9: 0},
	{ТайловыйФон2: 0},
	{ТайловыйФон3: 0},
	{Аудио: 0},
	{Якорь: 0},
	{Спрайт3: 0},
	{ТекстурныйШрифт: 0},
	{Ползунок: 0},
	{Тень: 0},
	{Спрайт11: 0},
	{ТайловыйФон4: 0},
	{Спрайт12: 0},
	{Кнопка: 0},
	{Спрайт13: 0},
	{Спрайт14: 0},
	{Кнопка2: 0},
	{Перетаскивание: 0},
	{Выживание: 0},
	{Спрайт15: 0},
	{Спрайт16: 0},
	{менюИграть: 0},
	{Спрайт17: 0},
	{Спрайт18: 0},
	{кнопкаИграть: 0},
	{яма: 0},
	{Переменная1: 0},
	{патроны: 0},
	{Спрайт6: 0},
	{Спрайт8: 0},
	{выПогиблиТекст: 0},
	{Спрайт10: 0},
	{Текст: 0},
	{Спрайт19: 0},
	{Спрайт20: 0},
	{какИграть: 0},
	{Спрайт21: 0},
	{ТекстурныйШрифт2: 0},
	{Текст2: 0},
	{ВводТекста: 0},
	{Текст3: 0},
	{"9патч": 0}
];

self.InstanceType = {
	ТайловыйФон: class extends self.ITiledBackgroundInstance {},
	Спрайт: class extends self.ISpriteInstance {},
	map: class extends self.ISpriteInstance {},
	Спрайт2: class extends self.ISpriteInstance {},
	Спрайт4: class extends self.ISpriteInstance {},
	Спрайт5: class extends self.ISpriteInstance {},
	враг: class extends self.ISpriteInstance {},
	Клавиатура: class extends self.IInstance {},
	mouse: class extends self.IInstance {},
	Спрайт7: class extends self.ISpriteInstance {},
	Пуля: class extends self.ISpriteInstance {},
	Спрайт9: class extends self.ISpriteInstance {},
	ТайловыйФон2: class extends self.ITiledBackgroundInstance {},
	ТайловыйФон3: class extends self.ITiledBackgroundInstance {},
	Аудио: class extends self.IInstance {},
	Спрайт3: class extends self.ISpriteInstance {},
	ТекстурныйШрифт: class extends self.ISpriteFontInstance {},
	Ползунок: class extends self.ISliderBarInstance {},
	Спрайт11: class extends self.ISpriteInstance {},
	ТайловыйФон4: class extends self.ITiledBackgroundInstance {},
	Спрайт12: class extends self.ISpriteInstance {},
	Кнопка: class extends self.IButtonInstance {},
	Спрайт13: class extends self.ISpriteInstance {},
	Спрайт14: class extends self.ISpriteInstance {},
	Кнопка2: class extends self.IButtonInstance {},
	Выживание: class extends self.ISpriteInstance {},
	Спрайт15: class extends self.ISpriteInstance {},
	Спрайт16: class extends self.ISpriteInstance {},
	менюИграть: class extends self.IButtonInstance {},
	Спрайт17: class extends self.ISpriteInstance {},
	Спрайт18: class extends self.ISpriteInstance {},
	кнопкаИграть: class extends self.ISpriteInstance {},
	яма: class extends self.ISpriteInstance {},
	патроны: class extends self.ITextInstance {},
	Спрайт6: class extends self.ISpriteInstance {},
	Спрайт8: class extends self.ISpriteInstance {},
	выПогиблиТекст: class extends self.ITextInstance {},
	Спрайт10: class extends self.ISpriteInstance {},
	Текст: class extends self.ITextInstance {},
	Спрайт19: class extends self.ISpriteInstance {},
	Спрайт20: class extends self.ISpriteInstance {},
	какИграть: class extends self.ISpriteInstance {},
	Спрайт21: class extends self.ISpriteInstance {},
	ТекстурныйШрифт2: class extends self.ISpriteFontInstance {},
	Текст2: class extends self.ITextInstance {},
	ВводТекста: class extends self.ITextInputInstance {},
	Текст3: class extends self.ITextInstance {},
	_9патч: class extends self.IWorldInstance {}
}